name: Deploy Frontend
on:
  workflow_dispatch:
  push:
    paths:
      - "frontend/**"

env:
  WORKING_DIRECTORY: "frontend"
  NODE_VERSION: "20"
#  VITE_API_URL: https://chatwithfabi-dev-backend.azurewebsites.net
#  VITE_GITHUB_URL: https://github.com/fabimass/rag-ai-chatbot

jobs:
  build-and-deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm ci

      - name: Run tests
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm test

      - name: Build the project
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: "${{ env.WORKING_DIRECTORY }}/dist"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          skip_app_build: true
