name: Deploy Frontend
on:
  workflow_dispatch:
  push:
    paths:
      - "frontend/**"

env:
  WORKING_DIRECTORY: 'frontend'
  NODE_VERSION: '20'            

jobs:
  build-and-deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm install

      - name: Build the project
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm run build
      
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: "${{ env.WORKING_DIRECTORY }}/dist"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          skip_app_build: true
