name: Deploy Backend
on:
  workflow_dispatch:
  push:
    paths:
      - "backend/**"

env:
  AZURE_WEBAPP_NAME: 'chatwithfabi-dev-backend'    
  WORKING_DIRECTORY: 'backend'        
  PYTHON_VERSION: '3.10'        
  STARTUP_COMMAND: 'gunicorn -w 4 -k uvicorn.workers.UvicornWorker myapp:app'           

jobs:
  build-and-deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: pip install -r requirements.txt

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: >
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }

      #- uses: azure/appservice-settings@v1
      #  with:
      #  app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #  mask-inputs: false
      #  general-settings-json: '{"linuxFxVersion": "PYTHON|${{ env.PYTHON_VERSION }}"}' #'General configuration settings as Key Value pairs'
      # deploy web app
      
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.WORKING_DIRECTORY }}
          startup-command: ${{ env.STARTUP_COMMAND }}
