name: Update Database

# The workflow runs when something change in the knowledge base or can be triggered manually
on:
  workflow_dispatch:
  push:
    paths:
      - "knowledge-base/**"

env:
  AZURE_COSMOS_DB_URI: ${{ secrets.AZURE_COSMOS_DB_URI }}
  AZURE_COSMOS_DB_KEY: ${{ secrets.AZURE_COSMOS_DB_KEY }}
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

jobs:
  update_db:
    name: Update Database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install azure-cosmos==4.7.0 langchain==0.2.11 langchain-community==0.2.10 markdown==3.6 unstructured==0.14.7

      - name: Run update-db script
        run: python .github/scripts/update-db.py
