name: Update Database (CSV)

# The workflow runs when something change in the knowledge base or can be triggered manually
on:
  workflow_dispatch:
  push:
    paths:
      - "knowledge-base/csv/**"

env:
  AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
  CSV_CONTAINER: ${{ vars.CSV_CONTAINER }}
  AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
  AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}

jobs:
  update_db:
    name: Update Database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install azure-storage-blob langchain==0.2.11 langchain-community==0.2.10 langchain-openai==0.1.22 pandas

      - name: Run script
        run: python -u .github/scripts/update-db-csv.py
