name: Update Database

# The workflow runs when something change in the knowledge base or can be triggered manually
on:
  workflow_dispatch:
  push:
    paths:
      - "knowledge-base/**"

env:
  AZURE_SEARCH_URI: ${{ secrets.AZURE_SEARCH_URI }}
  AZURE_SEARCH_KEY: ${{ secrets.AZURE_SEARCH_KEY }}
  AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
  AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}

jobs:
  update_db:
    name: Update Database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install langchain==0.2.11 langchain-community==0.2.10 markdown==3.6 unstructured==0.14.7 langchain-openai==0.1.22 azure-search-documents azure-identity

      - name: Get public IP address
        id: get_ip
        run: echo "PUBLIC_IP=$(curl -s https://api.ipify.org)" >> $GITHUB_ENV

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: >
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }

      - name: Add IP to Azure AI whitelist
        run: |
          az cognitiveservices account network-rule add \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_OPENAI_RESOURCE_NAME }} \
            --ip-address ${{ env.PUBLIC_IP }}

      - name: Run update-db script
        run: python .github/scripts/update-db.py
